version: '3.3'
services:
    laravel-app:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "${DOCKER_EXTERNAL_PORT}:80"
        volumes:
            - ./storage:/var/www/html/storage
        extra_hosts:
            - "host.docker.linux:${DOCKER_LOOPBACK_ADDRESS}"
