version: 2.1

jobs:
  deploy:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:WpSENHS8plY2GAAowwL3BNDYnU8K6TU5f/SAwJ0ZLt8"
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd $PROJECT_PATH && git pull && docker compose down && docker compose up --build -d"

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main # only deploy on the main branch
