name: Deploy To Vps

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH Agent and Add Private Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run commands on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER_HOST }} << 'EOF'
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chown -R ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ secrets.PATH_TO_PROJECT }}
            cd ${{ secrets.PATH_TO_PROJECT }}
            git rebase
            docker compose down
            docker-compose up --build -d
            echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S chown -R www-data:www-data ${{ secrets.PATH_TO_PROJECT }}
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
